version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t jorgepi/python-res-api:$TAG .
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push jorgepi/python-res-api:$TAG
          docker tag jorgepi/python-res-api:$TAG jorgepi/python-res-api:latest
          docker push jorgepi/python-res-api:latest
